package com.example.ruanstaron.mercadinho.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "BD_DEFINITIVO".
*/
public class BdDefinitivoDao extends AbstractDao<BdDefinitivo, Long> {

    public static final String TABLENAME = "BD_DEFINITIVO";

    /**
     * Properties of entity BdDefinitivo.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Cod_barras = new Property(1, Integer.class, "cod_barras", false, "COD_BARRAS");
        public final static Property Produto = new Property(2, String.class, "produto", false, "PRODUTO");
    }


    public BdDefinitivoDao(DaoConfig config) {
        super(config);
    }
    
    public BdDefinitivoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"BD_DEFINITIVO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"COD_BARRAS\" INTEGER," + // 1: cod_barras
                "\"PRODUTO\" TEXT);"); // 2: produto
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"BD_DEFINITIVO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, BdDefinitivo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer cod_barras = entity.getCod_barras();
        if (cod_barras != null) {
            stmt.bindLong(2, cod_barras);
        }
 
        String produto = entity.getProduto();
        if (produto != null) {
            stmt.bindString(3, produto);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, BdDefinitivo entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Integer cod_barras = entity.getCod_barras();
        if (cod_barras != null) {
            stmt.bindLong(2, cod_barras);
        }
 
        String produto = entity.getProduto();
        if (produto != null) {
            stmt.bindString(3, produto);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public BdDefinitivo readEntity(Cursor cursor, int offset) {
        BdDefinitivo entity = new BdDefinitivo( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1), // cod_barras
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // produto
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, BdDefinitivo entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setCod_barras(cursor.isNull(offset + 1) ? null : cursor.getInt(offset + 1));
        entity.setProduto(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(BdDefinitivo entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(BdDefinitivo entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(BdDefinitivo entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
}
