package com.example.ruanstaron.mercadinho.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.ruanstaron.mercadinho.db.Produto;
import com.example.ruanstaron.mercadinho.db.Lista;
import com.example.ruanstaron.mercadinho.db.Situacao;
import com.example.ruanstaron.mercadinho.db.Estado;
import com.example.ruanstaron.mercadinho.db.Cidade;
import com.example.ruanstaron.mercadinho.db.Mercado;
import com.example.ruanstaron.mercadinho.db.Lista_de_produtos;

import com.example.ruanstaron.mercadinho.db.ProdutoDao;
import com.example.ruanstaron.mercadinho.db.ListaDao;
import com.example.ruanstaron.mercadinho.db.SituacaoDao;
import com.example.ruanstaron.mercadinho.db.EstadoDao;
import com.example.ruanstaron.mercadinho.db.CidadeDao;
import com.example.ruanstaron.mercadinho.db.MercadoDao;
import com.example.ruanstaron.mercadinho.db.Lista_de_produtosDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig produtoDaoConfig;
    private final DaoConfig listaDaoConfig;
    private final DaoConfig situacaoDaoConfig;
    private final DaoConfig estadoDaoConfig;
    private final DaoConfig cidadeDaoConfig;
    private final DaoConfig mercadoDaoConfig;
    private final DaoConfig lista_de_produtosDaoConfig;

    private final ProdutoDao produtoDao;
    private final ListaDao listaDao;
    private final SituacaoDao situacaoDao;
    private final EstadoDao estadoDao;
    private final CidadeDao cidadeDao;
    private final MercadoDao mercadoDao;
    private final Lista_de_produtosDao lista_de_produtosDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        produtoDaoConfig = daoConfigMap.get(ProdutoDao.class).clone();
        produtoDaoConfig.initIdentityScope(type);

        listaDaoConfig = daoConfigMap.get(ListaDao.class).clone();
        listaDaoConfig.initIdentityScope(type);

        situacaoDaoConfig = daoConfigMap.get(SituacaoDao.class).clone();
        situacaoDaoConfig.initIdentityScope(type);

        estadoDaoConfig = daoConfigMap.get(EstadoDao.class).clone();
        estadoDaoConfig.initIdentityScope(type);

        cidadeDaoConfig = daoConfigMap.get(CidadeDao.class).clone();
        cidadeDaoConfig.initIdentityScope(type);

        mercadoDaoConfig = daoConfigMap.get(MercadoDao.class).clone();
        mercadoDaoConfig.initIdentityScope(type);

        lista_de_produtosDaoConfig = daoConfigMap.get(Lista_de_produtosDao.class).clone();
        lista_de_produtosDaoConfig.initIdentityScope(type);

        produtoDao = new ProdutoDao(produtoDaoConfig, this);
        listaDao = new ListaDao(listaDaoConfig, this);
        situacaoDao = new SituacaoDao(situacaoDaoConfig, this);
        estadoDao = new EstadoDao(estadoDaoConfig, this);
        cidadeDao = new CidadeDao(cidadeDaoConfig, this);
        mercadoDao = new MercadoDao(mercadoDaoConfig, this);
        lista_de_produtosDao = new Lista_de_produtosDao(lista_de_produtosDaoConfig, this);

        registerDao(Produto.class, produtoDao);
        registerDao(Lista.class, listaDao);
        registerDao(Situacao.class, situacaoDao);
        registerDao(Estado.class, estadoDao);
        registerDao(Cidade.class, cidadeDao);
        registerDao(Mercado.class, mercadoDao);
        registerDao(Lista_de_produtos.class, lista_de_produtosDao);
    }
    
    public void clear() {
        produtoDaoConfig.clearIdentityScope();
        listaDaoConfig.clearIdentityScope();
        situacaoDaoConfig.clearIdentityScope();
        estadoDaoConfig.clearIdentityScope();
        cidadeDaoConfig.clearIdentityScope();
        mercadoDaoConfig.clearIdentityScope();
        lista_de_produtosDaoConfig.clearIdentityScope();
    }

    public ProdutoDao getProdutoDao() {
        return produtoDao;
    }

    public ListaDao getListaDao() {
        return listaDao;
    }

    public SituacaoDao getSituacaoDao() {
        return situacaoDao;
    }

    public EstadoDao getEstadoDao() {
        return estadoDao;
    }

    public CidadeDao getCidadeDao() {
        return cidadeDao;
    }

    public MercadoDao getMercadoDao() {
        return mercadoDao;
    }

    public Lista_de_produtosDao getLista_de_produtosDao() {
        return lista_de_produtosDao;
    }

}
