package com.example.ruanstaron.mercadinho.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.example.ruanstaron.mercadinho.db.Lista;
import com.example.ruanstaron.mercadinho.db.Produtos;

import com.example.ruanstaron.mercadinho.db.ListaDao;
import com.example.ruanstaron.mercadinho.db.ProdutosDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig listaDaoConfig;
    private final DaoConfig produtosDaoConfig;

    private final ListaDao listaDao;
    private final ProdutosDao produtosDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        listaDaoConfig = daoConfigMap.get(ListaDao.class).clone();
        listaDaoConfig.initIdentityScope(type);

        produtosDaoConfig = daoConfigMap.get(ProdutosDao.class).clone();
        produtosDaoConfig.initIdentityScope(type);

        listaDao = new ListaDao(listaDaoConfig, this);
        produtosDao = new ProdutosDao(produtosDaoConfig, this);

        registerDao(Lista.class, listaDao);
        registerDao(Produtos.class, produtosDao);
    }
    
    public void clear() {
        listaDaoConfig.clearIdentityScope();
        produtosDaoConfig.clearIdentityScope();
    }

    public ListaDao getListaDao() {
        return listaDao;
    }

    public ProdutosDao getProdutosDao() {
        return produtosDao;
    }

}
