package com.example.ruanstaron.mercadinho.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "LISTA".
 */
@Entity
public class Lista {

    @Id
    private Long id;
    private String descricao;

    @Generated
    public Lista() {
    }

    public Lista(Long id) {
        this.id = id;
    }

    @Generated
    public Lista(Long id, String descricao) {
        this.id = id;
        this.descricao = descricao;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

}
