package com.example.ruanstaron.mercadinho.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "LISTA".
 */
@Entity
public class Lista {

    @Id
    private Long id;
    private String descricao;
    private Boolean recente;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Lista() {
    }

    public Lista(Long id) {
        this.id = id;
    }

    @Generated
    public Lista(Long id, String descricao, Boolean recente) {
        this.id = id;
        this.descricao = descricao;
        this.recente = recente;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public Boolean getRecente() {
        return recente;
    }

    public void setRecente(Boolean recente) {
        this.recente = recente;
    }

    // KEEP METHODS - put your custom methods here
    public Lista(String descricao, boolean recente){
        setDescricao(descricao);
        setRecente(recente);
    }
    // KEEP METHODS END

}
