package com.example.ruanstaron.mercadinho.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit.

/**
 * Entity mapped to table "PRODUTOS".
 */
@Entity
public class Produtos {
    private Long cod_barras;
    private String descricao;

    @Generated
    public Produtos() {
    }

    @Generated
    public Produtos(Long cod_barras, String descricao) {
        this.cod_barras = cod_barras;
        this.descricao = descricao;
    }

    public Long getCod_barras() {
        return cod_barras;
    }

    public void setCod_barras(Long cod_barras) {
        this.cod_barras = cod_barras;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

}
