package com.example.ruanstaron.mercadinho.db;

import java.util.List;
import java.util.ArrayList;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.SqlUtils;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "PRODUTOS".
*/
public class ProdutosDao extends AbstractDao<Produtos, Long> {

    public static final String TABLENAME = "PRODUTOS";

    /**
     * Properties of entity Produtos.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property ListaId = new Property(1, Long.class, "listaId", false, "LISTA_ID");
        public final static Property Cod_barras = new Property(2, Integer.class, "cod_barras", false, "COD_BARRAS");
        public final static Property Descricao = new Property(3, String.class, "descricao", false, "DESCRICAO");
        public final static Property Quantidade = new Property(4, Integer.class, "quantidade", false, "QUANTIDADE");
        public final static Property Valor = new Property(5, Double.class, "valor", false, "VALOR");
    }

    private DaoSession daoSession;


    public ProdutosDao(DaoConfig config) {
        super(config);
    }
    
    public ProdutosDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"PRODUTOS\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"LISTA_ID\" INTEGER," + // 1: listaId
                "\"COD_BARRAS\" INTEGER," + // 2: cod_barras
                "\"DESCRICAO\" TEXT," + // 3: descricao
                "\"QUANTIDADE\" INTEGER," + // 4: quantidade
                "\"VALOR\" REAL);"); // 5: valor
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"PRODUTOS\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Produtos entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long listaId = entity.getListaId();
        if (listaId != null) {
            stmt.bindLong(2, listaId);
        }
 
        Integer cod_barras = entity.getCod_barras();
        if (cod_barras != null) {
            stmt.bindLong(3, cod_barras);
        }
 
        String descricao = entity.getDescricao();
        if (descricao != null) {
            stmt.bindString(4, descricao);
        }
 
        Integer quantidade = entity.getQuantidade();
        if (quantidade != null) {
            stmt.bindLong(5, quantidade);
        }
 
        Double valor = entity.getValor();
        if (valor != null) {
            stmt.bindDouble(6, valor);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Produtos entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long listaId = entity.getListaId();
        if (listaId != null) {
            stmt.bindLong(2, listaId);
        }
 
        Integer cod_barras = entity.getCod_barras();
        if (cod_barras != null) {
            stmt.bindLong(3, cod_barras);
        }
 
        String descricao = entity.getDescricao();
        if (descricao != null) {
            stmt.bindString(4, descricao);
        }
 
        Integer quantidade = entity.getQuantidade();
        if (quantidade != null) {
            stmt.bindLong(5, quantidade);
        }
 
        Double valor = entity.getValor();
        if (valor != null) {
            stmt.bindDouble(6, valor);
        }
    }

    @Override
    protected final void attachEntity(Produtos entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Produtos readEntity(Cursor cursor, int offset) {
        Produtos entity = new Produtos( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // listaId
            cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2), // cod_barras
            cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3), // descricao
            cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4), // quantidade
            cursor.isNull(offset + 5) ? null : cursor.getDouble(offset + 5) // valor
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Produtos entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setListaId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setCod_barras(cursor.isNull(offset + 2) ? null : cursor.getInt(offset + 2));
        entity.setDescricao(cursor.isNull(offset + 3) ? null : cursor.getString(offset + 3));
        entity.setQuantidade(cursor.isNull(offset + 4) ? null : cursor.getInt(offset + 4));
        entity.setValor(cursor.isNull(offset + 5) ? null : cursor.getDouble(offset + 5));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Produtos entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Produtos entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Produtos entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getListaDao().getAllColumns());
            builder.append(" FROM PRODUTOS T");
            builder.append(" LEFT JOIN LISTA T0 ON T.\"LISTA_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Produtos loadCurrentDeep(Cursor cursor, boolean lock) {
        Produtos entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Lista lista = loadCurrentOther(daoSession.getListaDao(), cursor, offset);
        entity.setLista(lista);

        return entity;    
    }

    public Produtos loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Produtos> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Produtos> list = new ArrayList<Produtos>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Produtos> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Produtos> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
