package com.example.ruanstaron.mercadinho.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "PRODUTO".
 */
@Entity
public class Produto {

    @Id
    private Long cod_barras;
    private String descricao;
    private String descricao_usuario;
    private Boolean recente;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Produto() {
    }

    public Produto(Long cod_barras) {
        this.cod_barras = cod_barras;
    }

    @Generated
    public Produto(Long cod_barras, String descricao, String descricao_usuario, Boolean recente) {
        this.cod_barras = cod_barras;
        this.descricao = descricao;
        this.descricao_usuario = descricao_usuario;
        this.recente = recente;
    }

    public Long getCod_barras() {
        return cod_barras;
    }

    public void setCod_barras(Long cod_barras) {
        this.cod_barras = cod_barras;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public String getDescricao_usuario() {
        return descricao_usuario;
    }

    public void setDescricao_usuario(String descricao_usuario) {
        this.descricao_usuario = descricao_usuario;
    }

    public Boolean getRecente() {
        return recente;
    }

    public void setRecente(Boolean recente) {
        this.recente = recente;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
