package com.example.ruanstaron.mercadinho.db;

import java.util.List;
import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.query.Query;
import org.greenrobot.greendao.query.QueryBuilder;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "SITUACAO".
*/
public class SituacaoDao extends AbstractDao<Situacao, Long> {

    public static final String TABLENAME = "SITUACAO";

    /**
     * Properties of entity Situacao.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Descricao = new Property(1, String.class, "descricao", false, "DESCRICAO");
        public final static Property SituacaoId = new Property(2, Long.class, "situacaoId", false, "SITUACAO_ID");
    }

    private Query<Situacao> lista_de_produtos_SituacaoListQuery;

    public SituacaoDao(DaoConfig config) {
        super(config);
    }
    
    public SituacaoDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"SITUACAO\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"DESCRICAO\" TEXT," + // 1: descricao
                "\"SITUACAO_ID\" INTEGER);"); // 2: situacaoId
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"SITUACAO\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Situacao entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String descricao = entity.getDescricao();
        if (descricao != null) {
            stmt.bindString(2, descricao);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Situacao entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        String descricao = entity.getDescricao();
        if (descricao != null) {
            stmt.bindString(2, descricao);
        }
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Situacao readEntity(Cursor cursor, int offset) {
        Situacao entity = new Situacao( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1) // descricao
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Situacao entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setDescricao(cursor.isNull(offset + 1) ? null : cursor.getString(offset + 1));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Situacao entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Situacao entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Situacao entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    /** Internal query to resolve the "situacaoList" to-many relationship of Lista_de_produtos. */
    public List<Situacao> _queryLista_de_produtos_SituacaoList(Long situacaoId) {
        synchronized (this) {
            if (lista_de_produtos_SituacaoListQuery == null) {
                QueryBuilder<Situacao> queryBuilder = queryBuilder();
                queryBuilder.where(Properties.SituacaoId.eq(null));
                lista_de_produtos_SituacaoListQuery = queryBuilder.build();
            }
        }
        Query<Situacao> query = lista_de_produtos_SituacaoListQuery.forCurrentThread();
        query.setParameter(0, situacaoId);
        return query.list();
    }

}
