package tech.pucci.mercadinho.db;

import android.database.Cursor;
import android.database.sqlite.SQLiteStatement;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.Property;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.database.DatabaseStatement;
import org.greenrobot.greendao.internal.DaoConfig;
import org.greenrobot.greendao.internal.SqlUtils;

import java.util.ArrayList;
import java.util.List;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.
/** 
 * DAO for table "CIDADE".
*/
public class CidadeDao extends AbstractDao<Cidade, Long> {

    public static final String TABLENAME = "CIDADE";

    /**
     * Properties of entity Cidade.<br/>
     * Can be used for QueryBuilder and for referencing column names.
     */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property EstadoId = new Property(1, Long.class, "estadoId", false, "ESTADO_ID");
        public final static Property Descricao = new Property(2, String.class, "descricao", false, "DESCRICAO");
    }

    private DaoSession daoSession;


    public CidadeDao(DaoConfig config) {
        super(config);
    }
    
    public CidadeDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
        this.daoSession = daoSession;
    }

    /** Creates the underlying database table. */
    public static void createTable(Database db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "\"CIDADE\" (" + //
                "\"_id\" INTEGER PRIMARY KEY ," + // 0: id
                "\"ESTADO_ID\" INTEGER," + // 1: estadoId
                "\"DESCRICAO\" TEXT);"); // 2: descricao
    }

    /** Drops the underlying database table. */
    public static void dropTable(Database db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "\"CIDADE\"";
        db.execSQL(sql);
    }

    @Override
    protected final void bindValues(DatabaseStatement stmt, Cidade entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long estadoId = entity.getEstadoId();
        if (estadoId != null) {
            stmt.bindLong(2, estadoId);
        }
 
        String descricao = entity.getDescricao();
        if (descricao != null) {
            stmt.bindString(3, descricao);
        }
    }

    @Override
    protected final void bindValues(SQLiteStatement stmt, Cidade entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
 
        Long estadoId = entity.getEstadoId();
        if (estadoId != null) {
            stmt.bindLong(2, estadoId);
        }
 
        String descricao = entity.getDescricao();
        if (descricao != null) {
            stmt.bindString(3, descricao);
        }
    }

    @Override
    protected final void attachEntity(Cidade entity) {
        super.attachEntity(entity);
        entity.__setDaoSession(daoSession);
    }

    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    @Override
    public Cidade readEntity(Cursor cursor, int offset) {
        Cidade entity = new Cidade( //
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1), // estadoId
            cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2) // descricao
        );
        return entity;
    }
     
    @Override
    public void readEntity(Cursor cursor, Cidade entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setEstadoId(cursor.isNull(offset + 1) ? null : cursor.getLong(offset + 1));
        entity.setDescricao(cursor.isNull(offset + 2) ? null : cursor.getString(offset + 2));
     }
    
    @Override
    protected final Long updateKeyAfterInsert(Cidade entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    @Override
    public Long getKey(Cidade entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    @Override
    public boolean hasKey(Cidade entity) {
        return entity.getId() != null;
    }

    @Override
    protected final boolean isEntityUpdateable() {
        return true;
    }
    
    private String selectDeep;

    protected String getSelectDeep() {
        if (selectDeep == null) {
            StringBuilder builder = new StringBuilder("SELECT ");
            SqlUtils.appendColumns(builder, "T", getAllColumns());
            builder.append(',');
            SqlUtils.appendColumns(builder, "T0", daoSession.getEstadoDao().getAllColumns());
            builder.append(" FROM CIDADE T");
            builder.append(" LEFT JOIN ESTADO T0 ON T.\"ESTADO_ID\"=T0.\"_id\"");
            builder.append(' ');
            selectDeep = builder.toString();
        }
        return selectDeep;
    }
    
    protected Cidade loadCurrentDeep(Cursor cursor, boolean lock) {
        Cidade entity = loadCurrent(cursor, 0, lock);
        int offset = getAllColumns().length;

        Estado estado = loadCurrentOther(daoSession.getEstadoDao(), cursor, offset);
        entity.setEstado(estado);

        return entity;    
    }

    public Cidade loadDeep(Long key) {
        assertSinglePk();
        if (key == null) {
            return null;
        }

        StringBuilder builder = new StringBuilder(getSelectDeep());
        builder.append("WHERE ");
        SqlUtils.appendColumnsEqValue(builder, "T", getPkColumns());
        String sql = builder.toString();
        
        String[] keyArray = new String[] { key.toString() };
        Cursor cursor = db.rawQuery(sql, keyArray);
        
        try {
            boolean available = cursor.moveToFirst();
            if (!available) {
                return null;
            } else if (!cursor.isLast()) {
                throw new IllegalStateException("Expected unique result, but count was " + cursor.getCount());
            }
            return loadCurrentDeep(cursor, true);
        } finally {
            cursor.close();
        }
    }
    
    /** Reads all available rows from the given cursor and returns a list of new ImageTO objects. */
    public List<Cidade> loadAllDeepFromCursor(Cursor cursor) {
        int count = cursor.getCount();
        List<Cidade> list = new ArrayList<Cidade>(count);
        
        if (cursor.moveToFirst()) {
            if (identityScope != null) {
                identityScope.lock();
                identityScope.reserveRoom(count);
            }
            try {
                do {
                    list.add(loadCurrentDeep(cursor, false));
                } while (cursor.moveToNext());
            } finally {
                if (identityScope != null) {
                    identityScope.unlock();
                }
            }
        }
        return list;
    }
    
    protected List<Cidade> loadDeepAllAndCloseCursor(Cursor cursor) {
        try {
            return loadAllDeepFromCursor(cursor);
        } finally {
            cursor.close();
        }
    }
    

    /** A raw-style query where you can pass any WHERE clause and arguments. */
    public List<Cidade> queryDeep(String where, String... selectionArg) {
        Cursor cursor = db.rawQuery(getSelectDeep() + where, selectionArg);
        return loadDeepAllAndCloseCursor(cursor);
    }
 
}
