package tech.pucci.mercadinho.db;

import org.greenrobot.greendao.annotation.*;

// THIS CODE IS GENERATED BY greenDAO, EDIT ONLY INSIDE THE "KEEP"-SECTIONS

// KEEP INCLUDES - put your custom includes here
// KEEP INCLUDES END

/**
 * Entity mapped to table "ESTADO".
 */
@Entity
public class Estado {

    @Id
    private Long id;
    private String descricao;
    private String sigla;

    // KEEP FIELDS - put your custom fields here
    // KEEP FIELDS END

    @Generated
    public Estado() {
    }

    public Estado(Long id) {
        this.id = id;
    }

    @Generated
    public Estado(Long id, String descricao, String sigla) {
        this.id = id;
        this.descricao = descricao;
        this.sigla = sigla;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getDescricao() {
        return descricao;
    }

    public void setDescricao(String descricao) {
        this.descricao = descricao;
    }

    public String getSigla() {
        return sigla;
    }

    public void setSigla(String sigla) {
        this.sigla = sigla;
    }

    // KEEP METHODS - put your custom methods here
    // KEEP METHODS END

}
